# /Users/raymonddoran/.config/tmuxinator/spark.yml

name: morning
root: ~/

# Optional tmux socket
# socket_name: foo

# Note that the pre and post options have been deprecated and will be replaced by
# project hooks.

# Project hooks

# Runs on project start, always
# on_project_start: command

# Run on project start, the first time
# on_project_first_start: command

# Run on project start, after the first time
# on_project_restart: command

# Run on project exit ( detaching from tmux session )
# on_project_exit: command

# Run on project stop
# on_project_stop: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

windows:
  - spark:
      layout: main-vertical
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - edit_server:
          # cd to server code path
          - cd ~/development/auctionedge/cloud_integrations/spark_api/spark-api-appsync
          # open editor on this path.
          - e .
          # clear screen 
          - clear
        - client:
          # cd path/to/your/client/repo
          - cd ~/development/auctionedge/edge-spark-react
          # dev server start script
          - spark
        - edit_client:
          # cd into project dir
          - cd ~/development/auctionedge/edge-spark-react
          # get everything from remote
          - git fetch --all
          # open your editor
          - e .
          # clear screen 
          - clear
  - playground:
      layout: even-horizontal
      panes:
        - telehack:
          # changer to [YOUR_USERNAME]@telehack.com
          - ssh -p 6668 tdf@telehack.com
        - utility:
          # (mac) `brew install cowsay` // `cowsay [YOUR_PHRASE]`
          - cowsay good morning mr doran 
          # Give me a dad joke
          - dj